import React, { createContext, useContext, useState, useEffect, useCallback, useMemo, ReactNode } from 'react';

type Language = 'en' | 'he';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  isRTL: boolean;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.firm': 'The Firm',
    'nav.about': 'About',
    'nav.expertise': 'Expertise',
    'nav.realEstate': 'Real Estate',
    'nav.taxation': 'Tax and Compliance',
    'nav.estate': 'Family and Legacy',
    'nav.olim': 'Olim Hadashim and Returning Residents',
    'nav.commercial': 'Commercial and Civil',
    'nav.insights': 'Insights',
    'nav.globalClients': 'Global Clients',
    'nav.contact': 'Contact',
    'nav.schedule': 'Schedule Consultation',

    // Hero
    'hero.tagline': 'Where Legal Precision Meets Financial Judgment',
    'hero.title': 'Attorney in Israel',
    'hero.subtitle1': 'Complex transactions. Cross border matters. High stakes decisions. Advised with the legal depth and financial discipline they require.',
    'hero.subtitle2': 'Real estate, taxation, and estate planning delivered with clarity, structure, and financial foresight.',
    'hero.cta': 'Schedule a Consultation',

    // Conflict Section
    'conflict.title': 'Clarity Where Details Decide Outcomes',
    'conflict.body': 'We bring an international perspective shaped by financial training abroad and Israeli legal practice. Our bilingual counsel on domestic and cross border matters turns complex situations into clear, confident decisions.',
    'conflict.body2': 'We begin with verification and documentation so decisions are made with facts, not assumptions. Our role is to turn complex requirements into clear, structured decisions that protect your assets.',

    // Guide Section
    'guide.title': 'About the Firm',
    'guide.bio': 'The firm was founded on a single premise. The best legal advice on complex transactions requires financial literacy, not just legal knowledge. Maya Ziv holds an LLB from the College of Law and Business and a BBA in Finance from Baruch College, New York. This background shapes how every matter is approached.',
    'guide.punchline': 'We think ahead for our clients, using insight and judgment to anticipate their needs.',
    'guide.cta': 'More About the Firm',
    'parallax.quote': 'The details that seem technical are often the ones that determine the outcome.',

    // Methodology
    'method.title': 'A Structured Process From Verification to Execution',
    'method.subtitle': 'Clients receive a defined process, clear timelines, and rigorous due diligence with confidentiality and precision at every stage.',
    'method.step1.title': 'Verifying Ownership Before You Sign',
    'method.step1.desc': 'Early verification of ownership, liens, planning status, and zoning under Israeli law protects buyers and prevents exposure during property due diligence.',
    'method.step2.title': 'The Role of Legal Counsel in Cross Border Transactions',
    'method.step2.desc': 'Accurate drafting, regulatory oversight, and coordinated execution ensure secure property transfers and financial transactions across borders.',
    'method.step3.title': 'Coordinated Wills for Cross Border Estates',
    'method.step3.desc': 'Harmonizing Israeli and foreign wills prevents probate conflicts, ensures enforceability across jurisdictions, and protects families managing assets in multiple countries.',
    'method.step4.title': 'Prenuptial Agreements as Strategic Instruments',
    'method.step4.desc': 'Bilingual marital agreements approved by an Israeli court preserve financial clarity, protect property rights, and prevent future disputes for couples.',
    'method.step5.title': 'Early Tax Planning Prevents Unnecessary Exposure',
    'method.step5.desc': 'Structured preparation for purchase tax, capital gains, and reporting duties aligns Israeli obligations with foreign tax regimes, minimising liability.',
    'method.step6.title': 'Legal Structure Determines Long Term Outcomes',
    'method.step6.desc': 'The choice of ownership form, personal, joint, or corporate, directly shapes taxation, inheritance, and asset transfer, making early structuring essential.',

    // Practice Areas
    'practice.title': 'Areas of Practice',
    'practice.realEstate.title': 'Real Estate and Investment',
    'practice.realEstate.desc': 'Secure acquisition and tax planning.',
    'practice.taxation.title': 'International Tax and Compliance',
    'practice.taxation.desc': 'Cross border reporting and banking regulation.',
    'practice.estate.title': 'Family and Legacy Planning',
    'practice.estate.desc': 'Wills, inheritance, and intergenerational transfer.',
    'practice.learnMore': 'Learn More',
    'practice.olim.desc': 'Legal guidance for new immigrants and returning residents.',
    'practice.commercial.desc': 'Contracts, risk allocation, and business advisory.',
    'practice.additional.olim': 'Olim Hadashim and Returning Residents',
    'practice.additional.commercial': 'Commercial and Civil',

    // Insights
    'insights.title': 'Insights',
    'insights.readMore': 'Continue Reading',
    'insights.viewAll': 'View All Insights',
    'insights.hero.title': 'Legal Insights and Strategic Commentary',
    'insights.hero.subtitle': 'Practical guidance on Israeli real estate, cross border taxation, compliance, and legacy planning.',
    'insights.philosophy.title': 'Clarity for Cross Border Decisions',
    'insights.philosophy.body': 'Our insights are written to be practical. Structured explanations, key considerations, and common pitfalls to flag early. The goal is to help you ask better questions and understand the legal roadmap before committing to a transaction.',
    'article.notFound': 'Article Not Found',
    'article.backToInsights': 'Back to Insights',
    'article.readMore': 'Want to Read More?',
    'article.readMoreBody': 'Return to our insights page for more articles and professional content.',
    'article.allArticles': 'All Articles',
    'insights.article1.title': 'Buying Property in Israel as a Foreign Resident Legal and Tax Essentials',
    'insights.article1.snippet': 'Foreign residents must address unique legal tax and registration requirements when purchasing property in Israel. Clear due diligence and structured planning ensure a compliant and secure transaction.',
    'insights.article2.title': 'Wills and Inheritance in Israel Ensuring Cross Border Validity',
    'insights.article2.snippet': 'Cross border families must align Israeli inheritance procedures with foreign wills and overseas probate rules. Coordinated planning ensures enforceability and prevents unnecessary legal conflicts.',
    'insights.article3.title': 'Buying Property in Israel Essential Legal Checks for Domestic Buyers',
    'insights.article3.snippet': 'Domestic buyers must verify ownership rights planning status and contractual protections before committing to a property purchase. Structured legal checks reduce exposure and support a transparent and compliant transaction.',

    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.q1': 'When should I start tax planning?',
    'faq.a1': 'Tax planning must begin before any document is signed, ideally at negotiation stage. The applicable Purchase Tax rate depends on your residency status, whether this is your first property, and timing relative to any Aliyah. Getting this wrong is expensive and sometimes irreversible.',
    'faq.q2': 'How are buyer funds protected during the transaction?',
    'faq.a2': 'Buyer funds are released to the seller in stages, each tied to specific legal milestones. At each stage, a security interest (Hearat Azhara) is registered at the Land Registry in the buyer\'s favour. This ensures limited financial exposure if the transaction does not complete.',
    'faq.q3': 'Can I purchase property before making Aliyah?',
    'faq.a3': 'Yes. Non residents can purchase property in Israel. The more important question is the timing relative to your Aliyah date, as this affects Purchase Tax eligibility. In some cases purchasing before Aliyah preserves certain benefits. This analysis should be done before any commitment.',
    'faq.q4': 'Can I pay Israeli purchase tax in foreign currency?',
    'faq.a4': 'No. Purchase Tax payments to the Israeli Tax Authority are made in New Israeli Shekels. For clients transferring funds from abroad, this requires coordinating currency conversion, timing the transfer to limit exchange rate exposure, and ensuring the receiving Israeli bank accepts the funds. We manage this process as part of the transaction.',
    'faq.q5': 'Will the Israeli bank automatically accept my transfer?',
    'faq.a5': 'No. Israeli banks operate under strict anti money laundering requirements. An international transfer without prior documentation establishing the source of funds and purpose is likely to be held or returned. Preparing documentation in advance and coordinating with the bank before transferring is standard practice.',
    'faq.q6': 'When do I become a tax resident of Israel?',
    'faq.a6': 'Israeli tax residency is determined by the centre of life test, a factual assessment that includes physical presence of over 183 days in a tax year, as well as the location of your economic and personal ties. The consequences are significant and affect reporting obligations on worldwide income.',
    'faq.q7': 'Is a foreign will valid in Israel?',
    'faq.a7': 'A foreign will can be recognised in Israel but must go through a probate process including expert opinions on the relevant foreign law. This adds time and cost. The more reliable approach is to draft a separate Israeli will addressing Israeli assets, coordinated with your foreign will to avoid conflicts.',
    'faq.q8': 'Can I appoint an estate administrator residing outside Israel?',
    'faq.a8': 'Yes, though Israeli courts may require additional steps including guarantees before appointing a non resident administrator. The practical implications depend on the estate composition and complexity. We advise on executor selection with attention to the realistic demands of the role.',
    'faq.q9': 'What is the difference between an inheritance order and a probate order?',
    'faq.a9': 'A Probate Order (Kiyum Tzava\'a) confirms the validity of a will and authorises its execution. An Inheritance Order (Tzav Yerusha) is issued when no valid will exists, distributing the estate according to Israel\'s Succession Law. In cross border estates, coordination between jurisdictions is essential.',

    // CTA
    'cta.title': 'When the Matter Requires Both Legal and Financial Judgment',
    'cta.subtitle': 'Clients in Israel and abroad turn to Maya Ziv Law for transactions where precision matters. Inquiries welcome in Hebrew and English.',
    'cta.button': 'Schedule a Consultation',
    'cta.buttonSecondary': 'Initial Fit Assessment',

    // Footer
    'footer.brand': 'Attorney in Israel',
    'footer.services': 'Services',
    'footer.contact': 'Contact',
    'footer.legal': 'Legal',
    'footer.disclaimer': 'Disclaimer',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.disclaimerText': 'This website is for informational purposes only and does not constitute legal advice. No attorney-client relationship is formed by use of this site.',
    'footer.copyright': '© 2026 Maya Ziv Law. All rights reserved.',

    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': 'Begin your journey to legal clarity',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email Address',
    'contact.form.phone': 'Phone Number',
    'contact.form.inquiry': 'Nature of Inquiry',
    'contact.form.message': 'Your Message',
    'contact.form.submit': 'Send Message',
    'contact.form.success': 'Thank you for your message. We will respond within 24 to 48 hours.',
    'contact.inquiry.realEstate': 'Real Estate Transaction',
    'contact.inquiry.taxation': 'International Taxation',
    'contact.inquiry.estate': 'Estate Planning',
    'contact.inquiry.other': 'Other Legal Matter',

    // About Page
    'about.hero.title': 'Legal Counsel Built on Financial Discipline',
    'about.hero.subtitle': 'A boutique practice bridging the gap between legal strategy and financial discipline for international clients in Israel.',
    'about.philosophy.title': 'A Different Approach to Legal Practice',
    'about.philosophy.body': 'Maya Ziv Law advises private clients and businesses on matters where legal and financial decisions cannot be separated. The firm was founded on a single premise. Navigating complex transactions in Israel requires both legal rigour and genuine financial literacy. Maya Ziv holds an LLB from the College of Law and Business and a BBA in Finance and Accounting from Baruch College, New York. Prior to entering legal practice, she held roles at Citi Innovation Lab and Vornado Realty Trust. The firm is based in Israel and accepts clients in Hebrew and English.',
    'about.philosophy.body2': 'The firm was founded to serve both domestic and international clients who require bilingual legal counsel grounded in legal structure, financial insight, and clear communication. With an international academic background and early professional experience in finance and accounting, the practice brings analytical discipline and global professionalism into the Israeli legal environment. Clients benefit from structured, transparent guidance in matters that shape property, family planning, and long term personal decisions.',
    'about.attorney.title': 'Our Values',
    'about.attorney.body': 'Maya Ziv brings a unique perspective to the legal field. With international training and professional experience in finance and accounting, she approaches every case with financial rigor and a strategic view of the outcome.',
    'about.attorney.body2': 'We prioritise prevention over reaction. Matters are structured from the outset to reduce future exposure through documentation, verification, and clear contractual drafting. Clients receive a defined process, clear timelines, and full visibility on costs from the first engagement.',
    'about.serve.title': 'Who We Serve',
    'about.serve.body': 'The firm serves private individuals, families, and businesses who require legal advice at the intersection of law and finance. We take on work where the stakes are real and the margin for imprecision is narrow.',
    'about.serve.body2': 'Whether the matter is commercial or personal, local or cross border, we provide clear legal guidance focused on practical and reliable outcomes.',
    'about.expect.title': 'Why Clients Choose Us',
    'about.expect.intro': 'Engagement with the firm follows a defined, transparent path. We believe that clarity is the antidote to stress, especially when managing affairs remotely.',
    'about.expect.doc.title': 'Documentation First Approach',
    'about.expect.doc.desc': 'We begin with verification. Decisions are made based on facts and official records, not assumptions.',
    'about.expect.intl.title': 'International Transaction Expertise',
    'about.expect.intl.desc': 'A combination of international education, financial training, and Israeli legal practice enables precise bridging between cultures, regulations, and legal systems.',
    'about.expect.timeline.title': 'Domestic and International Perspective',
    'about.expect.timeline.desc': 'With roots in international education, financial training, and Israeli legal practice, the firm bridges cultural and regulatory differences with precision and foresight.',
    'about.expect.comm.title': 'Clarity and Transparency',
    'about.expect.comm.desc': 'Every engagement begins with defined expectations, structured timelines, and full visibility on costs, creating a stable and predictable client experience.',
    'about.expect.foresight.title': 'Strategic Foresight',
    'about.expect.foresight.desc': 'Matters are evaluated with legal precision, financial reasoning, and long term planning to ensure thoughtful and durable outcomes.',
    'about.cta.title': 'Start a Conversation',
    'about.cta.body': 'A clear plan is the first step to protecting assets and legacy.',
    'about.cta.button': 'Schedule a Consultation',

    // Service Pages - General
    'service.faq': 'Common Questions',

    // Estate Planning Page
    'estate.hero.title': 'Families with Assets in Israel and Connections Abroad',
    'estate.hero.subtitle': 'Structured legal planning for cross border wealth transfer, bilingual wills, and Enduring Power of Attorney under Israeli law.',
    'estate.challenge.title': 'Managing Family Wealth Across Jurisdictions',
    'estate.challenge.body': 'Families with assets in Israel and ties to other countries face a specific challenge. Ensuring that wealth passes to the next generation efficiently, without unnecessary tax events or procedural delays. Israeli inheritance law operates under its own rules. When foreign wills or assets in multiple countries are involved, the complexity increases significantly.\n\nThe firm develops structured estate plans integrating Israeli inheritance law with relevant foreign frameworks to prevent disputes and minimise probate delays.',
    'estate.challenge.body2': '',
    'estate.wills.title': 'Wills, Succession, and Cross Border Coordination',
    'estate.wills.body': 'The firm prepares Israel specific wills and comprehensive estate plans for clients who hold assets or maintain family connections across jurisdictions. Each document is drafted to meet Israeli formal and evidentiary requirements while coordinating with any existing foreign testamentary instruments.',
    'estate.wills.compliance.title': 'Drafting for Compliance',
    'estate.wills.compliance.desc': 'Preparing wills that satisfy the formal requirements of Israeli law, including witness provisions and language considerations for bilingual instruments.',
    'estate.wills.probate.title': 'Probate and Succession Orders',
    'estate.wills.probate.desc': 'Representing heirs in obtaining a Probate Order (Kiyum Tzava\'a) where a valid will exists, or a Succession Order (Tzvav Yerusha) where no will was left, through the Registrar of Inheritance or the Family Court.',
    'estate.wills.conflict.title': 'Minimising Conflict',
    'estate.wills.conflict.desc': 'Clear, unambiguous drafting that reduces the scope for interpretation disputes among beneficiaries. Where family dynamics are sensitive, the firm structures instruments to limit the grounds for challenge.',
    'estate.epa.title': 'Enduring Power of Attorney',
    'estate.epa.body': 'An Enduring Power of Attorney (EPA) allows you to designate trusted individuals to manage your personal, medical, and financial affairs in Israel should you become unable to do so. Unlike court appointed guardianship, an EPA lets you define the scope of authority and conditions in advance.',
    'estate.epa.body2': 'The firm prepares comprehensive, court compliant EPA documents that preserve your autonomy, reflect your intentions, and provide your family with clear instructions for a situation that most people prefer to plan for in advance rather than leave to judicial discretion.',
    'estate.process.title': 'How We Work',
    'estate.process.step1.title': 'Discovery and Mapping',
    'estate.process.step1.desc': 'We identify and map the client\'s assets, jurisdictions, beneficiaries, and family dynamics to understand the full legal and financial picture.',
    'estate.process.step2.title': 'Strategy and Structure',
    'estate.process.step2.desc': 'We propose a structure consisting of documents and coordination steps aligned with the client\'s objectives and the requirements of each jurisdiction involved.',
    'estate.process.step3.title': 'Drafting and Execution',
    'estate.process.step3.desc': 'Documents are drafted bilingually where required and executed in the form prescribed by Israeli law. For clients abroad, execution can take place at a consulate or before a notary with apostille.',
    'estate.process.step4.title': 'Safekeeping and Guidance',
    'estate.process.step4.desc': 'The firm provides instructions for secure storage and practical guidance for executors on future activation, so that the plan works when it is needed.',
    'estate.process.note': 'Clear scope, defined next steps, and documentation requirements are established from the outset.',
    'estate.tax.title': 'Tax Considerations for Cross Border Estates',
    'estate.tax.body': 'Israel\'s tax treatment of inheritance and lifetime transfers differs from that of many Western jurisdictions. Transferring assets, whether during one\'s lifetime or after death, may trigger tax events that vary depending on the nature of the asset, the residency of the parties, and the timing of the transfer.',
    'estate.tax.body2': 'The firm identifies potential tax exposure at the outset and coordinates with relevant advisors in other jurisdictions where needed. The objective is to structure the estate in a way that reduces avoidable liability and protects the value of the legacy passing to the next generation.',
    'estate.financial.title': 'Prenuptial and Postnuptial Agreements',
    'estate.financial.body': 'For international couples, the firm prepares bilingual agreements in English and Hebrew that address property ownership, financial arrangements, and asset protection across borders. Each agreement is drafted with precision and, where required, approved by a court or notary to ensure enforceability under Israeli law.',
    'estate.faq.q1': 'Do I need a separate will for my Israeli assets?',
    'estate.faq.a1': 'In many cross border situations, a dedicated Israel focused will can significantly reduce procedural friction and processing time for assets located in Israel. While foreign wills can often be validated here, the process is procedurally more complex and slower. The firm advises on whether a separate instrument is warranted based on the client\'s specific asset profile and jurisdictional exposure.',
    'estate.faq.q2': 'Can I appoint a foreign resident as my executor?',
    'estate.faq.a2': 'Yes, although it involves specific procedural requirements and practical considerations. A foreign resident executor may face challenges in managing day to day matters with Israeli banks, the Land Registry, and other institutions. The firm advises clients on the practical implications and, where appropriate, recommends appointing a local co executor or representative.',
    'estate.faq.q3': 'What is the difference between a Succession Order and a Probate Order?',
    'estate.faq.a3': 'A Probate Order (Tzvav Kiyum Tzava\'a) is issued when the deceased left a valid will and the court or Registrar confirms its validity. A Succession Order (Tzvav Yerusha) is issued when no valid will exists, in which case assets are distributed according to the rules of intestate succession under Israeli law.',
    'estate.faq.q4': 'Can probate proceedings be managed remotely?',
    'estate.faq.a4': 'Yes. The firm handles the entire process with the Registrar of Inheritance or the Family Court, as well as coordination with banks and the Land Registry, through a power of attorney. The client is not required to be physically present in Israel to obtain the order or to administer the estate.',
    'estate.cta.title': 'Planning That Protects What Matters',
    'estate.cta.body': 'Structured legal planning that supports your interests today and safeguards your family\'s position over time. Inquiries welcome in English and Hebrew.',
    'estate.cta.button': 'Schedule a Consultation',
    'estate.cta.note': 'Response within one to two business days.',

    // Real Estate Page
    'realestate.hero.title': 'Real Estate',
    'realestate.hero.subtitle': 'Advising private clients and investors on property transactions in Israel, with the financial discipline and legal precision that complex acquisitions require.',
    'realestate.approach.title': 'Where Legal Execution Meets Financial Judgment',
    'realestate.approach.body': 'For many clients, acquiring property in Israel is both a personal milestone and a significant financial commitment. Israeli real estate law is technically demanding. Title verification, planning compliance, tax classification, and staged payments each carry consequences if mishandled. The firm provides end to end legal counsel across the entire acquisition process.',
    'realestate.approach.body2': 'Maya Ziv\'s prior experience in financial and operational roles, including positions at Citi Innovation Lab and Vornado Realty Trust, informs the firm\'s approach to property transactions. The result is legal advice that accounts not only for regulatory compliance but also for the financial structure, timing, and long term consequences of every decision.',
    'realestate.risk.title': 'Identifying and Neutralising Risk Before You Commit',
    'realestate.risk.intro': 'Israeli real estate law places the burden of verification squarely on the buyer. The firm\'s due diligence process is designed to surface and address exposure before any binding commitment is made.',
    'realestate.risk.liabilities.title': 'Title and Encumbrances',
    'realestate.risk.liabilities.desc': 'Confirming registered ownership and detecting any liens, mortgages, caveats, or third party rights that could affect the transaction or limit future use.',
    'realestate.risk.planning.title': 'Planning and Zoning Compliance',
    'realestate.risk.planning.desc': 'Verifying that the property was built in accordance with approved permits and that no open enforcement proceedings, deviation orders, or zoning restrictions exist that could trigger fines or devaluation.',
    'realestate.risk.tax.title': 'Tax Exposure',
    'realestate.risk.tax.desc': 'Analysing the client\'s residency status, acquisition timing, and transaction structure to identify the applicable Purchase Tax bracket and any Capital Gains exposure, and to ensure that no avoidable liability is triggered.',
    'realestate.tax.title': 'Tax and Regulatory Considerations',
    'realestate.tax.body': 'Purchase Tax (Mas Rechisha) in Israel varies based on the buyer\'s classification. Israeli resident, foreign resident, new immigrant (Oleh), or returning resident (Toshav Hozer). Misclassification can result in significant overpayment.',
    'realestate.tax.body2': 'The firm assesses each client\'s tax position at the outset. Filings are prepared with careful attention to deadlines, documentation, and eligibility for lawful relief. Clients who qualify for reduced rates receive structured guidance on securing those benefits.',
    'realestate.diligence.title': 'Comprehensive Legal Due Diligence',
    'realestate.diligence.body': 'A secure acquisition begins with verification. Before any contractual commitment, the firm conducts a thorough legal audit of the property, covering registered title, encumbrances, planning history, building permits, and any pending administrative or legal proceedings that could affect the asset.',
    'realestate.diligence.body2': 'This structured analysis ensures that the property you acquire corresponds to the legal and physical reality you were shown. Clients make decisions based on documented facts, not assumptions.',
    'realestate.remote.title': 'Representation for Clients Outside Israel',
    'realestate.remote.body': 'Clients who reside abroad can complete the entire acquisition remotely. The firm acts under an irrevocable power of attorney, signed at an Israeli consulate or before a notary with apostille. This enables full legal representation without requiring physical presence in Israel.',
    'realestate.remote.body2': 'The firm manages every step of the process on the client\'s behalf. Contract negotiation, due diligence, tax filings, coordination with the seller\'s counsel, and registration at the Land Registry. Communication is maintained throughout in English and Hebrew.',
    'realestate.faq.q1': 'When should tax planning begin?',
    'realestate.faq.a1': 'Tax planning on an Israeli property transaction must begin before any document is signed, ideally at the negotiation stage. The applicable Purchase Tax rate depends on your residency status, whether this is your first property in Israel, and the timing of the transaction relative to any Aliyah or relocation. Getting this wrong after the fact is expensive and in some cases irreversible. We assess your tax position at the outset, as part of the transaction structure.',
    'realestate.faq.q2': 'How are funds protected during the transaction?',
    'realestate.faq.a2': 'Buyer funds are released to the seller in stages, each tied to specific legal milestones. At each stage, a security interest (Hearat Azhara) is registered at the Land Registry in the buyer\'s favour. This ensures limited financial exposure if the transaction does not complete.',
    'realestate.faq.q3': 'Can I buy property before making Aliyah?',
    'realestate.faq.a3': 'Yes. Non residents can purchase property in Israel. The more important question is the timing of the purchase relative to your Aliyah date, as this affects your Purchase Tax eligibility. In some cases, purchasing before making Aliyah preserves certain benefits. In others, waiting is the better structure. This analysis is specific to each client\'s situation and should be done before any commitment is made.',
    'realestate.cta.title': 'Invest with Precision',
    'realestate.cta.body': 'Begin your property acquisition with a clear legal and financial strategy. Inquiries welcome in English and Hebrew.',
    'realestate.cta.button': 'Schedule a Consultation',

    // Taxation Page
    'tax.hero.title': 'Tax and Compliance',
    'tax.hero.subtitle': 'Structuring cross border tax positions and regulatory compliance for private clients and businesses with connections to Israel.',
    'tax.context.title': 'Financial Discipline Applied to Legal Strategy',
    'tax.context.body': 'Tax and regulatory compliance determine whether transactions are approved, funded, and completed. Every transaction carries implications in Israel and potentially in other jurisdictions. A misstep in classification, timing, or documentation can result in penalties, blocked funds, or lost treaty benefits.',
    'tax.context.body2': 'The firm approaches every engagement with the financial discipline that comes from Maya Ziv\'s background in finance and accounting. By integrating tax planning into the legal process from the outset, we minimise regulatory friction and protect the client\'s standing with Israeli institutions.',
    'tax.realEstate.title': 'Real Estate Tax Planning',
    'tax.realEstate.body': 'Tax assessment is the critical first step of any property transaction in Israel. The brackets for Purchase Tax (Mas Rechisha) and Capital Gains Tax (Mas Shevach) vary based on the client\'s residency classification, the nature of the property, and whether other properties are held.',
    'tax.realEstate.assessment.title': 'Pre Contract Assessment',
    'tax.realEstate.assessment.desc': 'Calculating projected tax liabilities, identifying the correct residency classification, and confirming eligibility for any applicable relief before a binding commitment is made.',
    'tax.realEstate.ownership.title': 'Ownership and Structure Planning',
    'tax.realEstate.ownership.desc': 'Evaluating registration and ownership options aligned with the client\'s status, family structure, and long term financial objectives.',
    'tax.realEstate.filing.title': 'Filing and Reporting',
    'tax.realEstate.filing.desc': 'Preparing and submitting all declarations to the Israel Tax Authority with precise documentation, within the statutory deadlines, to avoid interest, penalties, and administrative delays.',
    'tax.banking.title': 'Banking Regulation and Source of Funds',
    'tax.banking.body': 'Transferring capital to or from Israel requires strict compliance with anti money laundering regulations and banking guidelines. Israeli banks conduct their own due diligence on incoming funds, and transfers that are not supported by clear documentation of source and purpose may be delayed, rejected, or flagged for further review.',
    'tax.banking.body2': 'The firm prepares comprehensive source of funds files and coordinates directly with the receiving bank to facilitate smooth acceptance. We also assist in preparing ongoing tax declarations, aligning Israeli reporting obligations with international requirements and relevant treaty provisions to reduce the risk of double taxation.',
    'tax.serve.title': 'Is This Service Right for You?',
    'tax.serve.body': 'This service is designed for clients who prioritize a documented, transparent process. We partner with international investors and private clients who understand that compliance is the key to asset safety.',
    'tax.serve.compliance': 'Compliance First',
    'tax.serve.compliance.desc': 'Every engagement is built on documented verification, transparent timelines, and a structured process that prioritises regulatory accuracy over speed.',
    'tax.serve.firstStep': 'First Step',
    'tax.serve.firstStep.desc': 'Engagement begins with a structured assessment of your tax position, residency status, and reporting obligations to establish a clear compliance roadmap.',
    'tax.crossBorder.title': 'Coordination with International Tax Obligations',
    'tax.crossBorder.body': 'Israel\'s network of bilateral tax treaties may affect how income, gains, and reporting obligations are treated depending on the client\'s jurisdiction of residence or citizenship.',
    'tax.crossBorder.body2': 'The firm identifies potential treaty related considerations and coordinates with the client\'s foreign tax advisors to maintain a consistent tax position across jurisdictions. While we do not file foreign tax returns, we ensure that every Israeli legal action is documented and communicated clearly to the client\'s global advisory team.',
    'tax.olim.title': 'Tax Planning for Olim Hadashim and Returning Residents',
    'tax.olim.body': 'New immigrants (Olim Hadashim) and qualifying returning residents may be eligible for significant tax reliefs, including the ten year exemption on foreign income. These benefits are subject to strict eligibility criteria, classification rules, and timing. The firm helps clients position themselves correctly.',
    'tax.faq.q1': 'Can I pay Israeli purchase tax in foreign currency?',
    'tax.faq.a1': 'No. Purchase Tax payments to the Israeli Tax Authority are made in New Israeli Shekels. For clients transferring funds from abroad, this requires coordinating currency conversion, timing the transfer to limit exchange rate exposure, and ensuring the receiving Israeli bank accepts the funds. We manage this process as part of the transaction.',
    'tax.faq.q2': 'Will the Israeli bank automatically accept my transfer?',
    'tax.faq.a2': 'No. Israeli banks operate under strict anti money laundering regulations and conduct independent due diligence on every incoming international transfer. A transfer that is not accompanied by clear documentation of source, purpose, and beneficial ownership may be held, returned, or subjected to extended review. The firm prepares a structured source of funds file in advance to facilitate acceptance.',
    'tax.faq.q3': 'When do I become a tax resident of Israel?',
    'tax.faq.a3': 'Israeli tax residency is determined by a "centre of life" test, which considers factors such as the location of your permanent home, your economic and social ties, and the number of days spent in Israel during the relevant tax year. The determination is fact specific and has significant consequences for reporting and liability. We advise clients on how their actions and timing affect their classification.',
    'tax.cta.title': 'Compliance Built on Clarity',
    'tax.cta.body': 'Start with a structured plan that turns uncertainty into documented decisions. Inquiries welcome in English and Hebrew.',
    'tax.cta.button': 'Schedule a Consultation',

    // Olim & Returning Residents Page
    'olim.hero.title': 'Legal Counsel for Olim Hadashim and Returning Residents',
    'olim.hero.subtitle': 'A structured legal framework for your transition to Israel. Tax positioning, property acquisition, banking compliance, and asset integration.',
    'olim.context.title': 'A New Chapter, Structured from Day One',
    'olim.context.body': 'Relocating to Israel is both a personal milestone and a complex legal transition. The decisions you make in the first months, from residency classification to property purchase timing, will shape your tax position and financial structure for years to come. Each client receives a clear roadmap tailored to their situation.',
    'olim.context.body2': '',
    'olim.framework.title': 'The Soft Landing Framework',
    'olim.framework.planning.title': 'Pre Arrival Planning',
    'olim.framework.planning.desc': 'Reviewing the client\'s residency status, asset profile, and family structure before arrival. Identifying timing sensitive decisions and positioning the client to preserve eligibility for available benefits.',
    'olim.framework.property.title': 'Property Acquisition Coordination',
    'olim.framework.property.desc': 'Managing legal aspects of purchasing a first property in Israel, including due diligence, tax filing, and registration, with attention to purchase timing and residency status.',
    'olim.framework.banking.title': 'Banking and Capital Transfers',
    'olim.framework.banking.desc': 'Preparing source of funds documentation, coordinating with the receiving Israeli bank, and ensuring that international transfers are accepted without unnecessary delay or complication.',
    'olim.framework.peace.title': 'Bilingual, Cross Border Support',
    'olim.framework.peace.desc': 'The firm communicates in both English and Hebrew and coordinates with the client\'s foreign advisors where needed. The goal is to translate complex Israeli legal processes into clear, practical steps, providing confidence during one of life\'s most significant transitions.',
    'olim.tax.title': 'Tax Positioning for Olim Hadashim and Returning Residents',
    'olim.tax.body': 'New immigrants and qualifying returning residents may be eligible for specific reliefs, including reduced Purchase Tax rates and the ten year exemption from reporting on foreign source income. These benefits are subject to strict eligibility criteria, and correct timing, classification, and documentation are essential to securing them.',
    'olim.tax.body2': 'The firm helps clients understand how their specific circumstances affect their classification, what documentation is required, and how the timing of their arrival and first transactions should be structured to support a compliant and tax efficient transition into the Israeli system.',
    'olim.clients.title': 'Who This Service Is For',
    'olim.clients.body': 'This practice area is designed for individuals and families relocating to Israel who hold significant assets, foreign income, or cross border financial structures. Clients who value a disciplined, compliance first approach will benefit most.',
    'olim.expect.title': 'What to Expect',
    'olim.expect.body': 'Engagement begins with a structured intake. A tailored documentation checklist, a residency and tax status assessment, and a coordinated roadmap with clearly defined next steps. Every client knows what is required, when it is required, and why it matters.',
    'olim.expect.item1': 'Documentation checklist tailored to your situation',
    'olim.expect.item2': 'Residency and tax status mapping',
    'olim.expect.item3': 'Coordinated roadmap with defined next steps',
    'olim.cta.title': 'Start Your Transition on Solid Ground',
    'olim.cta.body': 'Begin with a structured roadmap and a clear understanding of your legal and financial position. Inquiries welcome in English and Hebrew.',
    'olim.cta.button': 'Schedule a Consultation',

    // Commercial & Civil Page
    'commercial.hero.title': 'Commercial and Civil',
    'commercial.hero.subtitle': 'Protecting business interests through disciplined contracts, structured risk allocation, and Israel based representation for cross border matters.',
    'commercial.philosophy.title': 'Precision Before Disputes',
    'commercial.philosophy.body': 'In commercial engagements, the strength of your position depends on the quality of your contracts. Whether drafting a shareholders\' agreement, negotiating an exit, or structuring a cross border arrangement, the firm evaluates each matter through three lenses. Contractual rights, financial exposure, and future enforceability.',
    'commercial.philosophy.body2': 'This approach reflects the firm\'s core discipline. Legal analysis that is informed by financial understanding. Clients receive structured guidance that supports negotiation, dispute resolution, or formal proceedings, depending on what the matter requires.',
    'commercial.services.title': 'Core Services',
    'commercial.services.contracts.title': 'Contract Drafting and Review',
    'commercial.services.contracts.desc': 'Structuring shareholders\' agreements, partnership agreements, commercial leases, service contracts, and other commercial instruments with precise definitions, clear allocation of risk, and enforceable remedies.',
    'commercial.services.negotiation.title': 'Negotiation and Risk Positioning',
    'commercial.services.negotiation.desc': 'Strategic legal counsel before signature or during escalation to improve the client\'s leverage, manage exposure, and define acceptable outcomes.',
    'commercial.services.dispute.title': 'Dispute Strategy and Resolution',
    'commercial.services.dispute.desc': 'Pre litigation analysis, settlement frameworks, and litigation management where required. The firm prioritises the client\'s commercial interest.',
    'commercial.services.crossborder.title': 'Cross Border Documentation',
    'commercial.services.crossborder.desc': 'Coordination with overseas counsel and localisation of foreign contracts and judgments for enforcement or recognition in Israel.',
    'commercial.crossborder.title': 'Business Interests Across Borders',
    'commercial.crossborder.body': 'The firm serves as the local legal representative for clients who reside abroad but maintain active commercial or financial interests in Israel. This includes investors, business owners, and executives who require ongoing Israeli counsel or need to protect specific rights and obligations within the Israeli legal system.',
    'commercial.crossborder.body2': 'Whether enforcing a foreign contract in Israel, protecting shareholder rights overseas, or managing a dispute with an Israeli counterpart, the firm provides practical, on the ground representation across jurisdictions.',
    'commercial.clients.title': 'Who We Work With',
    'commercial.clients.body': 'The commercial practice serves business owners, investors, executives, and private clients who require disciplined legal counsel on contracts, asset protection, and complex disputes. Whether the engagement is a single transaction or an ongoing advisory relationship, the firm provides the same level of analytical depth and personal attention.',
    'commercial.cta.title': 'Protect Your Commercial Position',
    'commercial.cta.body': 'Begin with a contract review, a risk assessment, or a dispute strategy consultation. Confidential and documented. Inquiries welcome in English and Hebrew.',
    'commercial.cta.button': 'Schedule a Consultation',
  },
  he: {
    // Navigation
    'nav.firm': 'המשרד',
    'nav.about': 'אודות',
    'nav.expertise': 'תחומי מומחיות',
    'nav.realEstate': 'נדל״ן',
    'nav.taxation': 'מיסוי',
    'nav.estate': 'תכנון עזבונות, ירושות וצוואות',
    'nav.olim': 'עולים חדשים ותושבים חוזרים',
    'nav.commercial': 'דיני מסחר ואזרחי',
    'nav.insights': 'מאמרים',
    'nav.globalClients': 'לקוחות בינלאומיים',
    'nav.contact': 'צור קשר',
    'nav.schedule': 'תיאום פגישת ייעוץ',

    // Hero
    'hero.tagline': 'העתיד מחייך למי שמתכונן מראש',
    'hero.title': 'מאיה זיו | עורכת דין בישראל',
    'hero.subtitle1': 'מלווים כל לקוח בבהירות, בבטחון ובמצוינות',
    'hero.subtitle2': 'החלטות אסטרטגיות בעולם גלובאלי',
    'hero.cta': 'בקשת ייעוץ חסוי',

    // Conflict Section
    'conflict.title': 'בהירות במקום שהפרטים קובעים את התוצאה',
    'conflict.body': 'עבור לקוחותינו בישראל ומעבר לים, אנו מביאים פרספקטיבה בינלאומית המשלבת הכשרה פיננסית גלובלית עם פרקטיקה משפטית בישראל, המעוגנת בהבנה עמוקה של הדין המקומי. שילוב זה מאפשר לנו להעניק ייעוץ דו-לשוני בסוגיות מקומיות וחוצות גבולות, תוך מחשבה מתמדת בצורכי הלקוח ובניית מערכות יחסים ארוכות טווח. אנו מתרגמים מצבים מורכבים להחלטות ממוקדות ובטוחות.',
    'conflict.body2': 'אנו מתחילים באימות ותיעוד כדי שהחלטות יתקבלו על בסיס עובדות, לא הנחות. התפקיד שלנו הוא להפוך דרישות מורכבות להחלטות ברורות ומובנות שמגנות על הנכסים שלכם.',

    // Guide Section
    'guide.title': 'אודות המשרד',
    'guide.bio': 'המשרד הוקם כדי להעניק ללקוחות ליווי משפטי מקומי ובינלאומי, המבוסס על רקע אקדמי בהיר. המשרד מביא ניסיון מקצועי ותקשורת פיננסית קפדנית, על מנת לתכנן משפטית וגלובלית בהתאם לסטנדרטים אנליטיים. לקוחות המשרד נהנים מליווי שקוף ומובנה בסוגיות תכנון נכסיהם, לטווח הארוך, תוך שמירה על ההחלטות האישיות והמשפחתיות שלהם.',
    'guide.punchline': 'אנו חושבים צעד אחד קדימה עבור לקוחותינו ומקבלים החלטות אסטרטגיות לחזות את אתגרי המחר.',
    'guide.cta': 'קראו עוד על המשרד',
    'parallax.quote': 'תכנון משפטי המעוגן בהשלכות כלכליות ארוכות טווח, מהיום הראשון.',

    // Methodology
    'method.title': 'תהליך מובנה מאימות ועד ביצוע',
    'method.subtitle': 'לקוחותינו מקבלים תהליך מוגדר, לוחות זמנים ברורים ובדיקת נאותות קפדנית תוך שמירה על חיסיון ודיוק בכל שלב.',
    'method.step1.title': 'חשיבות בדק על הנכס',
    'method.step1.desc': 'בדיקה מוקדמת של זכויות בעלות, שעבודים, סטטוס תכנוני וייעוד מגנה על רוכשים ומונעת סיכונים משפטיים בעת רכישת נכס.',
    'method.step2.title': 'תפקיד הייעוץ המשפטי בעסקאות בין לאומיות',
    'method.step2.desc': 'בדיקת נאותות, פיקוח וליווי משפטי מקיימים העברת זכויות וניהול כספים בטוח בעסקאות חוצות גבולות.',
    'method.step3.title': 'תיאום צוואות למשפחות בינלאומיות',
    'method.step3.desc': 'תיאום בין צוואות שנערכו בישראל ומעבר לים מונע סכסוכי ירושה, מבטיח אכיפה משפטית, והגנה מיטבית על הרכוש והמשפחה.',
    'method.step4.title': 'הסכם ממון ככלי אסטרטגי',
    'method.step4.desc': 'הסכמים המאושרים על ידי ערכאה מוסמכת שומרים על בהירות פיננסית, מגנים על זכויות רכוש ומונעים מחלוקות עתידיות.',
    'method.step5.title': 'תכנון מס מוקדם ככלי לחסכון כלכלי',
    'method.step5.desc': 'תכנון מקדים והערכות מוקדמת לתשלומי מס רכישה, מס שבח ודיווחים שוטפים בישראל או במדינות מעבר לים מפחית את החשיפה למס ומונע כפל תשלומים.',
    'method.step6.title': 'המבנה המשפטי קובע את התוצאה',
    'method.step6.desc': 'האם הבעלות תהיה אישית, משותפת או תאגידית? הבחירה משפיעה על מיסוי, ירושה, פרטיות והעברת נכסים, לכן חשוב להחליט נכון מההתחלה.',

    // Practice Areas
    'practice.title': 'תחומי עסוק',
    'practice.realEstate.title': 'נדל"ן והשקעות',
    'practice.realEstate.desc': 'ליווי רכישה ומכירה, בדיקות נאותות ורישום זכויות.',
    'practice.taxation.title': 'מיסוי',
    'practice.taxation.desc': 'תכנון מס מקרקעין, ייעוץ תושבות ו-Compliance בנקאי.',
    'practice.estate.title': 'תכנון עזבונות, ירושות וצוואות',
    'practice.estate.desc': 'עריכת צוואות, ייפוי כוח מתמשך וניהול עיזבונות.',
    'practice.learnMore': 'למידע נוסף',
    'practice.olim.desc': 'ליווי משפטי לעולים חדשים ותושבים חוזרים.',
    'practice.commercial.desc': 'חוזים, הקצאת סיכונים וייעוץ עסקי.',
    'practice.additional.olim': 'עולים חדשים ותושבים חוזרים',
    'practice.additional.commercial': 'משפט מסחרי ואזרחי',

    // Insights
    'insights.title': 'מאמרים נבחרים',
    'insights.readMore': 'קרא עוד',
    'insights.viewAll': 'קרא עוד',
    'insights.hero.title': 'תובנות משפטיות ופרשנות אסטרטגית',
    'insights.hero.subtitle': 'הנחיות מעשיות בנושאי נדל"ן בישראל, מיסוי חוצה גבולות, ציות ותכנון מורשת.',
    'insights.philosophy.title': 'בהירות להחלטות חוצות גבולות',
    'insights.philosophy.body': 'התובנות שלנו נכתבות להיות מעשיות. הסברים מובנים, שיקולים מרכזיים ומלכודות נפוצות לסימון מוקדם. המטרה היא לעזור לכם לשאול שאלות טובות יותר ולהבין את המפה המשפטית לפני התחייבות לעסקה.',
    'article.notFound': 'המאמר לא נמצא',
    'article.backToInsights': 'חזרה למאמרים',
    'article.readMore': 'רוצים לקרוא עוד?',
    'article.readMoreBody': 'חזרו לדף התובנות שלנו לעוד מאמרים ותכנים מקצועיים.',
    'article.allArticles': 'כל המאמרים',
    'insights.article1.title': 'רכישת נכס בישראל לתושב חוץ',
    'insights.article1.snippet': 'מדריך ליסודות המיסוי, העברת כספים ורישום בטוח בטאבו.',
    'insights.article2.title': 'ירושות וצוואות חוצות גבולות',
    'insights.article2.snippet': 'כיצד להבטיח תוקף משפטי לנכסים בישראל כחלק מעיזבון גלובלי.',
    'insights.article3.title': 'בדיקות לפני קניית דירה',
    'insights.article3.snippet': 'חריגות בנייה, היטל השבחה והגנות משפטיות בחוזה הרכישה.',

    // FAQ
    'faq.title': 'שאלות נפוצות',
    'faq.q1': 'מתי כדאי להתחיל בתכנון המס?',
    'faq.a1': 'הערכת המס צריכה להתבצע בשלב המקדמי עוד לפני החתימה על מסמך מחייב. זיהוי סטטוס התושבות והטבות המס (לעולים חדשים או תושבים חוזרים) בשלב המשא ומתן מאפשר אופטימיזציה של חבויות המס ומונע הפתעות פיננסיות.',
    'faq.q2': 'כיצד מובטחת הגנה על כספי הרוכש במהלך העסקה?',
    'faq.a2': 'הכספים לרוב מוחזקים בחשבון נאמנות (Escrow) ומשוחררים למוכר רק ובהתאם לעמידה באבני דרך משפטיות שנקבעו מראש בחוזה המכר, כגון רישום הערת אזהרה לטובתכם בלשכת רישום המקרקעין.',
    'faq.q3': 'האם ניתן לרכוש נכס לפני ביצוע העלייה לישראל?',
    'faq.a3': 'בהחלט. המשרד מלווה עולים חדשים בתכנון המבנה המשפטי והמיסויי של הרכישה עוד לפני המעבר הפיזי לישראל, תוך בחינת תזמון העסקה במטרה למקסם את הטבות המס המגיעות להם.',
    'faq.q4': 'האם אפשר לשלם מס רכישה ישראלי במטבע חוץ?',
    'faq.a4': 'לא. התשלום לרשויות המס בישראל מתבצע בשקלים (ILS). המשרד מסייע בתיאום ההמרה והעברת התשלום מחשבונות בינלאומיים בצורה המדויקת ביותר בהתאם לדרישות הדין.',
    'faq.q5': 'האם הבנק הישראלי יקבל את ההעברה שלי אוטומטית?',
    'faq.a5': 'לא. המערכת הבנקאית בישראל פועלת תחת כללי ציות (Compliance) קפדניים. ללא הכנה מוקדמת של תיק מקור כספים ואישור מוקדם מהבנק, העברות בינלאומיות עלולות להיחסם. אנו מכינים את תיק התיעוד מראש למניעת עיכובים.',
    'faq.q6': 'מתי אני הופך לתושב מס בישראל?',
    'faq.a6': 'תושבות לצרכי מס נקבעה פי מבחן מרכז החיים (שהייה של מעל 183 ימים בשנה) ולא רק על בסיס אזרחות. אנו מייעצים לגבי הקריטריונים המשפטיים ובוחנים כיצד הנוכחות שלכם בישראל משפיעה על הסטטוס.',
    'faq.q7': 'האם צוואה זרה תקפה בישראל?',
    'faq.a7': 'מימוש צוואה זרה מחייב הליך של אישור צוואה לפי דין זר המערב חוות דעת מומחים. עריכת צוואה ישראלית נפרדת המיועדת לנכסים בארץ מפשטת באופן משמעותי את התהליך וחוסכת עלויות.',
    'faq.q8': 'האם ניתן למנות מנהל עיזבון המתגורר מחוץ לישראל?',
    'faq.a8': 'כן, אך לעיתים נדרשים צעדים פרוצדורליים נוספים כגון העמדת ערבויות להבטחת ניהול העיזבון. המשרד מנחה את הלקוח בבחירת המבצעים בהתאם לנסיבות.',
    'faq.q9': 'מה ההבדל בין צו ירושה לצו קיום צוואה?',
    'faq.a9': 'צו קיום צוואה ניתן כאשר המנוח הותיר צוואה תקפה המסדירה את חלוקת רכושו. צו ירושה ניתן בהיעדר צוואה ואז חלוקת העיזבון מתבצעת לפי הוראות חוק הירושה הישראלי.',

    // CTA
    'cta.title': 'הלקוחות שלנו חשובים לנו',
    'cta.subtitle': 'אנחנו מחויבים לליווי משפטי מדויק, בהירות מחשבתית וביטחון אסטרטגי בכל החלטה',
    'cta.button': 'צור קשר',
    'cta.buttonSecondary': 'בדיקת התאמה ראשונית',

    // Footer
    'footer.brand': 'עורכת דין בישראל',
    'footer.services': 'שירותים',
    'footer.contact': 'צור קשר',
    'footer.legal': 'משפטי',
    'footer.disclaimer': 'הסתייגות',
    'footer.privacy': 'מדיניות פרטיות',
    'footer.terms': 'תנאי שימוש',
    'footer.disclaimerText': 'התוכן באתר זה מיועד למידע כללי בלבד ואינו מהווה ייעוץ משפטי. שימוש באתר או יצירת קשר דרכו אינם יוצרים יחסי עורך דין-לקוח.',
    'footer.copyright': '© 2026 עו"ד מאיה זיו. כל הזכויות שמורות.',

    // Contact Page
    'contact.title': 'צור קשר',
    'contact.subtitle': 'התחילו את המסע שלכם לבהירות משפטית',
    'contact.form.name': 'שם מלא',
    'contact.form.email': 'כתובת אימייל',
    'contact.form.phone': 'מספר טלפון',
    'contact.form.inquiry': 'אופי הפנייה',
    'contact.form.message': 'ההודעה שלכם',
    'contact.form.submit': 'שלח הודעה',
    'contact.form.success': 'תודה על פנייתכם. נחזור אליכם תוך 24 עד 48 שעות.',
    'contact.inquiry.realEstate': 'עסקת נדל"ן',
    'contact.inquiry.taxation': 'מיסוי בינלאומי',
    'contact.inquiry.estate': 'ירושות וצוואות',
    'contact.inquiry.other': 'עניין משפטי אחר',

    // About Page
    'about.hero.title': 'אודות המשרד',
    'about.hero.subtitle': 'פרקטיקת בוטיק המגשרת בין אסטרטגיה משפטית למשמעת פיננסית עבור לקוחות בינלאומיים בישראל.',
    'about.philosophy.title': 'גישה שונה לפרקטיקה משפטית',
    'about.philosophy.body': 'המשרד הוקם כדי להעניק ללקוחות מקומיים ובינלאומיים ליווי משפטי דו-לשוני, המבוסס על תכנון משפטי קפדני, ראייה פיננסית ותקשורת בהירה. מתוך רקע אקדמי בינלאומי וניסיון מקצועי בפיננסים ובחשבונאות, המשרד מביא משמעת אנליטית וסטנדרטים גלובליים אל עולם המשפט הישראלי.',
    'about.philosophy.body2': 'לקוחות המשרד נהנים מליווי מובנה ושקוף בסוגיות המעצבות את נכסיהם, את התכנון המשפחתי ואת ההחלטות האישיות לטווח הארוך.',
    'about.attorney.title': 'הערכים שלנו',
    'about.attorney.body': 'מאיה זיו מביאה פרספקטיבה ייחודית לתחום המשפט. עם הכשרה בינלאומית וניסיון מקצועי בפיננסים ובחשבונאות, היא ניגשת לכל תיק עם קפדנות פיננסית וראייה אסטרטגית של התוצאה.',
    'about.attorney.body2': 'אנו מעדיפים מניעה ומבנה. העבודה שלנו נועדה להפחית חיכוך, להגן על עמדות מוקדם ולמנוע סכסוכים לפני שהם מתעוררים. על ידי צפייה מראש של מכשולים רגולטוריים ומבנון נכון של עסקאות מההתחלה, המטרה היא ליצור יציבות - להבטיח שהסידורים המשפטיים שלכם ישרתו את המורשת הפיננסית והאישית שלכם לטווח ארוך.',
    'about.serve.title': 'את מי אנו משרתים',
    'about.serve.body': 'הפרקטיקה שלנו מתאימה ללקוחות שמעדיפים בהירות, שקדנות ותוצאות מתמשכות על פני פתרונות מהירים. אנו שותפים למשקיעים בינלאומיים, תושבים חוזרים ומשפחות הדורשים רמה גבוהה של מעורבות ומדיניות של "אפס הפתעות". אנו תופסים הזדמנויות לחדש ולצמוח.',
    'about.serve.body2': 'בין אם העניין מסחרי או אישי, מקומי או חוצה גבולות, אנו מספקים הדרכה משפטית ברורה המתמקדת בתוצאות מעשיות ואמינות.',
    'about.expect.title': 'מדוע הלקוחות שלנו בוחרים בנו',
    'about.expect.intro': 'המשרד מלווה את לקוחותיו, בין אם הם מתגוררים בישראל או מעבר לים, תוך שילוב ציפיות ברורות ותקשורת קפדנית.',
    'about.expect.doc.title': 'פרספקטיבה מקומית ובינלאומית',
    'about.expect.doc.desc': 'המשרד מלווה תושבי ישראל ולקוחות העולים לישראל או מתגוררים מעבר לים, תוך הקפדה על תקשורת ברורה, תיאום ציפיות ושילוב חלק בין מערכות משפט שונות.',
    'about.expect.intl.title': 'מומחיות בעסקאות בינלאומיות',
    'about.expect.intl.desc': 'שילוב של השכלה בין לאומית, הכשרה פיננסית ופרקטיקה משפטית בישראל מאפשר גישור מדויק בין תרבויות, רגולציות ומערכות דין.',
    'about.expect.timeline.title': 'שקיפות ובהירות',
    'about.expect.timeline.desc': 'אנו מאמינים במערכות יחסים ארוכות טווח, כל התקשרות נפתחת בהגדרת מסגרת ברורה, לוחות זמנים מדויקים ושקיפות שמייצרת בעבור לקוחותינו ביטחון.',
    'about.expect.comm.title': 'חשיבה אסטרטגית',
    'about.expect.comm.desc': 'כל סוגיה נבחנת בדיוק משפטי, בהיגיון פיננסי ובתכנון פתרונות עמידים וארוכי טווח.',
    'about.expect.foresight.title': 'מחויבות אישית',
    'about.expect.foresight.desc': 'לקוחותינו מקבלים ליווי מעורכת הדין הבכירה, בשיקול דעת מקצועי ומחויבות מלאה למטרותיהם.',
    'about.cta.title': 'התחילו שיחה',
    'about.cta.body': 'תוכנית ברורה היא הצעד הראשון להגנה על נכסים ומורשת.',
    'about.cta.button': 'תיאום שיחת ייעוץ',

    // Service Pages - General
    'service.faq': 'שאלות נפוצות',

    // Estate Planning Page
    'estate.hero.title': 'משפחות עם נכסים בישראל וזיקה בינלאומית',
    'estate.hero.subtitle': 'אסטרטגיות משפטיות להעברת עושר חוצה גבולות, צוואות דו-לשוניות וייפוי כוח מתמשך (ישראל).',
    'estate.challenge.title': 'ניהול הון משפחתי בין תחומי שיפוט',
    'estate.challenge.body': 'משפחות עם נכסים בישראל וזיקות לחו"ל מתמודדות עם נוף משפטי ייחודי. הליכי ירושה ישראליים לעתים קרובות מתממשקים עם חוקים זרים, יוצרים קונפליקטים פוטנציאליים בנוגע לסמכות שיפוט וחבות מס. צוואה ישראלית סטנדרטית לעתים רחוקות מספיקה לעיזבון רב-לאומי.',
    'estate.challenge.body2': 'המשרד מפתח תוכניות עיזבון מובנות ללקוחות ישראליים ובינלאומיים למניעת סכסוכים, הימנעות מעיכובי פרובייט והפחתת חשיפה למיסוי כפול. התהליך משלב דיני ירושה ישראליים עם מסגרות משפטיות זרות רלוונטיות, תומך בלקוחות המתגוררים בישראל או בחו"ל המחזיקים בנכסים או קשרים משפחתיים במספר תחומי שיפוט. גישה מתואמת זו מבטיחה שכל ירושה מועברת ביעילות ובהתאם לכוונת הלקוח.',
    'estate.wills.title': 'משפחות בעלות נכסים בישראל וזיקה בינלאומית',
    'estate.wills.body': 'המשרד מגבש מתווי תכנון עיזבון מובנים עבור לקוחות ישראלים ובינלאומיים במטרה למנוע מחלוקות, לייתר עיכובים בהליכי אישור הצו ולצמצם חשיפה לכפל מס. תהליך העבודה מסנכרן בין חוק הירושה הישראלי לבין מערכות דינים זרות רלוונטיות ומספק מענה ללקוחות המתגוררים בישראל או מחוץ למדינה המחזיקים בנכסים או בזיקות משפחתיות במספר תחומי שיפוט במקביל. גישה מתואמת זו מבטיחה את העברת העיזבון ביעילות ובהתאם לכוונת המוריש.',
    'estate.wills.compliance.title': 'עריכת צוואות תואמות דין',
    'estate.wills.compliance.desc': 'ניסוח צוואות העומדות בדרישות הראייתיות והפורמליות של הדין הישראלי, הכולל התייחסות ספציפית לנכסים בארץ שבבעלות תושבים זרים.',
    'estate.wills.probate.title': 'ניהול ירושות חוצות גבולות',
    'estate.wills.probate.desc': 'תיאום הליכי צו בין רשויות בישראל לבין ערכאות מחוץ למדינה למזעור חשיפה למסי עיזבון בינלאומיים וקיצור משך הטיפול הרגולטורי.',
    'estate.wills.conflict.title': 'ייפוי כוח מתמשך',
    'estate.wills.conflict.desc': 'עריכת הסדר משפטי המאפשר לקבוע מראש את זהות מנהלי העניינים.',
    'estate.epa.title': 'ייפוי כוח מתמשך',
    'estate.epa.body': 'ייפוי כוח מתמשך (EPA) הוא מכשיר צופה פני עתיד לשמירה על שליטה בעתידכם. הוא מאפשר לכם למנות נציגים מהימנים לנהל את ענייניכם האישיים והפיננסיים בישראל, אם יתעורר הצורך.',
    'estate.epa.body2': 'בניגוד לאפוטרופסות הממונה על ידי בית משפט, EPA מאפשר לכם להגדיר את היקף הסמכות מראש. המשרד מכין מסמכים מקיפים התואמים לבית המשפט ששומרים על האוטונומיה, הכוונה והיציבות המשפחתית שלכם.',
    'estate.process.title': 'איך אנחנו עובדים. תהליך התכנון',
    'estate.process.step1.title': 'גילוי ומיפוי',
    'estate.process.step1.desc': 'אנו ממפים את הנכסים, תחומי השיפוט והדינמיקה המשפחתית שלכם כדי להבין את התמונה המשפטית המלאה.',
    'estate.process.step2.title': 'אסטרטגיה ומבנה',
    'estate.process.step2.desc': 'אנו מציעים מבנה (מסמכים ושלבי תיאום) המותאם למטרות ולתחומי השיפוט שלכם.',
    'estate.process.step3.title': 'ניסוח וביצוע',
    'estate.process.step3.desc': 'במידת הצורך, מסמכים מנוסחים דו-לשונית ונחתמים בצורה המתאימה בישראל או בחו"ל כדי לעמוד בדרישות ראייתיות.',
    'estate.process.step4.title': 'שמירה והדרכה',
    'estate.process.step4.desc': 'אנו מספקים הנחיות לאחסון והדרכה למבצעים שלכם לגבי הפעלה עתידית.',
    'estate.process.note': 'היקף ברור, שלבים מוגדרים ודרישות תיעוד נקבעים מראש.',
    'estate.tax.title': 'שיקולי מס לעיזבונות חוצי גבולות',
    'estate.tax.body': 'משטר המס של ישראל בנוגע לירושות והעברות שונה מתחומי שיפוט מערביים רבים. העברת נכסים בין אם בחיים ובין אם לאחר מכן דורשת תזמון קפדני כדי להימנע מאירועי מס מיותרים.',
    'estate.tax.body2': 'אנו מסמנים נקודות מגע מס פוטנציאליות בישראל ומתאמים עם יועצים רלוונטיים בעת הצורך. המטרה שלנו היא להעריך את מבנה העיזבון שלכם כדי להפחית חשיפה שניתן להימנע ממנה ולהגן על ערך המורשת העוברת לדור הבא.',
    'estate.financial.title': 'הסכמי ממון טרום-נישואין ולאחר נישואין',
    'estate.financial.body': 'הסכמים דו-לשוניים באנגלית ובעברית מבטיחים בהירות ואכיפות לזוגות בינלאומיים. כל הסכם מנוסח בדיוק ומאושר על ידי בית משפט או נוטריון, תוך שמירה על בעלות רכושית וסידורים פיננסיים חוצי גבולות.',
    'estate.faq.q1': 'האם אני צריך צוואה נפרדת לנכסים הישראליים שלי?',
    'estate.faq.a1': 'במצבים חוצי גבולות רבים, צוואה ממוקדת ישראל יכולה להפחית חיכוך פרוצדורלי עבור נכסים בישראל. בעוד שצוואות זרות לעתים קרובות ניתנות לאישור כאן, התהליך מורכב יותר ואיטי יותר.',
    'estate.faq.q2': 'האם אני יכול למנות תושב חוץ כמבצע שלי?',
    'estate.faq.a2': 'כן, אם כי הדבר דורש צעדים פרוצדורליים ספציפיים. אנו מדריכים לקוחות לגבי ההשלכות המעשיות של מינוי מבצעים המתגוררים מחוץ לישראל.',
    'estate.faq.q3': 'מה ההבדל בין צו ירושה לצו קיום צוואה?',
    'estate.faq.a3': 'צו קיום צוואה ניתן כאשר המנוח הותיר צוואה תקפה. צו ירושה ניתן כאשר אין צוואה תקפה, ובמקרה זה הנכסים מחולקים לפי דיני הירושה הישראליים.',
    'estate.faq.q4': 'האם ניתן לנהל הליכי פרובייט מרחוק?',
    'estate.faq.a4': 'כן. אנו מטפלים בתהליך מול הרשם והבנקים באמצעות ייפוי כוח, כך שאינכם נדרשים להיות נוכחים בישראל לקבלת הצו.',
    'estate.cta.title': 'תכנון לעתיד',
    'estate.cta.body': 'תכנון משפטי ברור שתומך באינטרסים שלכם היום ולאורך זמן.',
    'estate.cta.button': 'תיאום שיחת ייעוץ',
    'estate.cta.note': 'מענה תוך 1-2 ימי עסקים',

    // Real Estate Page
    'realestate.hero.title': 'מקרקעין ונדל"ן',
    'realestate.hero.subtitle': 'ייעוץ מקיף לקונים בינלאומיים. בדיקת נאותות, אסטרטגיית מס ורישום מאובטח.',
    'realestate.approach.title': 'יותר מעסקה. השקעה אסטרטגית',
    'realestate.approach.body': 'עבור לקוחות רבים רכישת נכס בישראל היא יותר מהשקעה; זהו ציון דרך אישי והחלטה פיננסית לטווח ארוך. המשרד מעניק ליווי משפטי מלא הכולל ביצוע בדיקת נאותות (Due Diligence), סקירה חוזית ורישום בלשכת רישום המקרקעין. התהליך כולו מנוהל בבהירות, משמעת וראיית הנולד במטרה לקדם עסקה בטוחה ושקופה.',
    'realestate.approach.body2': 'הניסיון המקצועי של עו״ד מאיה זיו בתפקידים פיננסיים ותפעוליים, כולל עבודה ב-Citi Innovation Lab ו-Vornado Realty Trust, מעצב את הגישה של המשרד לעסקאות נדל״ן. התוצאה היא ייעוץ משפטי המתחשב לא רק בציות רגולטורי, אלא גם במבנה הפיננסי, בתזמון ובהשלכות ארוכות הטווח של כל החלטה.',
    'realestate.risk.title': 'צמצום חשיפה בשוק מורכב',
    'realestate.risk.intro': 'הדין הישראלי מטיל את חובת הבדיקה על הקונה ("ייזהר הקונה"). הליך בדיקת הנאותות המבוצע בעבור לקוחות המשרד נועד לזהות סיכונים ולצמצם את החשיפה בטרם התחייבות חוזית.',
    'realestate.risk.liabilities.title': 'חבויות נסתרות ושעבודים',
    'realestate.risk.liabilities.desc': 'איתור עיקולים, חובות, משכנתאות או זכויות צד ג הרשומים על הנכס.',
    'realestate.risk.planning.title': 'תכנון ורישוי (Zoning)',
    'realestate.risk.planning.desc': 'אימות התאמת הנכס להיתרי בנייה למניעת חשיפה לקנסות או ירידת ערך עתידית.',
    'realestate.risk.tax.title': 'חשיפת מס',
    'realestate.risk.tax.desc': 'זיהוי סוגיות עיתוי או סיווג תושבות העלולות לגרור חבויות מס מיותרות.',
    'realestate.tax.title': 'שיקולי רגולציה ומיסוי מקרקעין',
    'realestate.tax.body': 'מס הרכישה בישראל הוא דינמי. תושבים המנהלים זיקה בינלאומית כפופים לרוב למדרגות מס שונות בהשוואה לעולים חדשים או לתושבים חוזרים. מיסוי המקרקעין משתנה בהתאם לפרופיל הלקוח (תושב מחוץ לישראל, עולה חדש או תושב חוזר), כאשר לכל סיווג מדרגות מס והטבות ייחודיות.',
    'realestate.tax.body2': 'אנו מיישמים בקיאות רגולטורית לצורך הכנה והגשת דיווחים בלוחות זמנים קשיחים ובדיוק מרבי. המטרה היא מיצוי זכויות חוקיות וניטרול עיכובים בירוקרטיים.',
    'realestate.diligence.title': 'בדיקות נאותות קפדניות (Due Diligence)',
    'realestate.diligence.body': 'עסקה בטוחה מתחילה באימות עובדות. לפני יצירת התחייבות כלשהי אנו מבצעים ביקורת משפטית מקיפה של הנכס הכוללת אימות בעלות בטאבו, בדיקת שעבודים וסקירה תכנונית.',
    'realestate.diligence.body2': 'ניתוח מובנה זה מאפשר ללקוח לקבל החלטה מושכלת המבוססת על עובדות מתועדות ומבטיח שהנכס הנרכש תואם את המצג המשפטי.',
    'realestate.remote.title': 'ייצוג ללקוחות השוהים מחוץ לישראל (רכישה מרחוק)',
    'realestate.remote.body': 'לקוחות המתגוררים מחוץ לישראל יכולים להשלים את תהליך הרכישה מרחוק. הייצוג מבוצע באמצעות ייפוי כוח נוטריוני ספציפי (הנחתם בקונסוליה או בפני נוטריון עם אפוסטיל) המאפשר השלמה יעילה וחוקית של העסקה.',
    'realestate.remote.body2': 'מודל זה מאפשר לנו לנהל את העסקה משלב המשא ומתן ועד לרישום הסופי ומעניק ללקוח יכולת להשלים את הרכישה בביטחון מלא גם כאשר הוא נמצא בזירה הבינלאומית.',
    'realestate.faq.q1': 'מתי צריך להתחיל בתכנון מס?',
    'realestate.faq.a1': 'יש להעריך חבות מס לפני חתימה על כל זיכרון דברים או חוזה. מבנון מוקדם מאפשר לנו להגיש בקשה לפטורים רלוונטיים (כגון הטבות עולים) ולמנוע תשלום יתר.',
    'realestate.faq.q2': 'איך הכספים מוגנים במהלך העסקה?',
    'realestate.faq.a2': 'כספים מוחזקים בדרך כלל בנאמנות (Escrow) ומשוחררים לפי לוח זמנים קפדני המקושר לאבני דרך משפטיות, כגון רישום "הערת אזהרה" לטובתכם.',
    'realestate.faq.q3': 'האם אני יכול לקנות נכס לפני עלייה?',
    'realestate.faq.a3': 'כן. תושבי חוץ יכולים לרכוש נכס. אנו מייעצים כיצד תזמון הרכישה ביחס לתאריך העלייה שלכם משפיע על הטבות מס הרכישה שלכם.',
    'realestate.cta.title': 'אבטחו את ההשקעה שלכם',
    'realestate.cta.body': 'התחילו את הרכישה עם אסטרטגיה משפטית ופיננסית ברורה.',
    'realestate.cta.button': 'תיאום שיחת ייעוץ',

    // Taxation Page
    'tax.hero.title': 'מיסוי ותאימות',
    'tax.hero.subtitle': '',
    'tax.context.title': 'עדשה פיננסית על אסטרטגיה משפטית',
    'tax.context.body': 'מיסוי ותאימות מעצבים האם עסקאות מאושרות, ממומנות ומושלמות. בין אם רוכשים נכס או מעבירים כספים, כל עסקה נושאת השלכות בישראל ופוטנציאלית בחו"ל.',
    'tax.context.body2': 'אנו ניגשים לכל מקרה עם משמעת פיננסית. על ידי שילוב תכנון מס בתהליך המשפטי, אנו ממזערים חיכוך רגולטורי, תומכים בתאימות מלאה ותומכים במעמדכם מול מוסדות פיננסיים.',
    'tax.realEstate.title': 'אסטרטגיית מס וניהול הון',
    'tax.realEstate.body': 'הערכת מס מוקדמת היא רובד קריטי בניהול עסקת מקרקעין. המשרד מתמחה באופטימיזציה של חבויות מס עבור תושבי ישראל ולקוחות בינלאומיים המנהלים נכסים בתחומי שיפוט שונים.',
    'tax.realEstate.assessment.title': 'תכנון מס מקדמי',
    'tax.realEstate.assessment.desc': 'חישוב חבויות מס שבח ומס רכישה צפויות ובחינת זכאות לפטורים רלוונטיים טרם יצירת התחייבות חוזית.',
    'tax.realEstate.ownership.title': 'ציות בנקאי (Compliance)',
    'tax.realEstate.ownership.desc': 'העברת הון לישראל דורשת עמידה ברגולציה מחמירה של איסור הלבנת הון. המשרד מלווה את הלקוח בבניית תיק מקור כספים (Source of Funds) סדור להבטחת קליטת הכספים במערכת הבנקאית.',
    'tax.realEstate.filing.title': 'תיאום מס בינלאומי',
    'tax.realEstate.filing.desc': 'בחינת השלכות המס בישראל אל מול חובות דיווח זרות במטרה למנוע כפל מס ולהגן על הערך הכלכלי של ההשקעה.',
    'tax.banking.title': 'רגולציה בנקאית ומקור כספים',
    'tax.banking.body': 'העברת כספים לישראל או ממנה דורשת הקפדה על רגולציה בנקאית ותקני מניעת הלבנת הון. כל עסקה מנוהלת בתיאום עם מוסדות פיננסיים ישראליים כדי להבטיח תאימות ל-FATCA, דרישות AML והנחיות בנקאות מקומיות.',
    'tax.banking.body2': 'המשרד גם מסייע בהכנה והגשה של הצהרות מס שוטפות, מתאם דיווח ישראלי עם התחייבויות בינלאומיות ואמנות רלוונטיות, מפחית את הסיכון למיסוי כפול ותומך ביציבות פיננסית ומשפטית לטווח ארוך בין תחומי שיפוט.',
    'tax.serve.title': 'האם שירות זה מתאים לכם?',
    'tax.serve.body': 'שירות זה מיועד ללקוחות שמעדיפים תהליך מתועד ושקוף. אנו שותפים למשקיעים בינלאומיים ולקוחות פרטיים שמבינים שתאימות היא המפתח לבטיחות הנכסים.',
    'tax.serve.compliance': 'תאימות קודמת',
    'tax.serve.compliance.desc': 'כל התקשרות מבוססת על אימות מתועד, לוחות זמנים שקופים ותהליך מובנה המעדיף דיוק רגולטורי.',
    'tax.serve.firstStep': 'צעד ראשון',
    'tax.serve.firstStep.desc': 'ההתקשרות מתחילה בהערכה מובנית של מעמד המס, סטטוס התושבות וחובות הדיווח שלכם, לצורך בניית מפת דרכים ברורה לתאימות.',
    'tax.crossBorder.title': 'תיאום עם התחייבויות בינלאומיות',
    'tax.crossBorder.body': 'רשת האמנות של ישראל עשויה להשפיע על אופן הטיפול בהכנסות מסוימות וחובות דיווח, בהתאם לתחום השיפוט שלכם.',
    'tax.crossBorder.body2': 'אנו מסמנים שיקולים פוטנציאליים הקשורים לאמנות ומתאמים עם יועצי המס הזרים שלכם. בעוד שאנו לא מגישים דוחות מס זרים, אנו מבטיחים שהפעולות המשפטיות הישראליות שלכם מתקשרות בבהירות לצוות הגלובלי שלכם לשמירה על עמדת מס עקבית.',
    'tax.olim.title': 'תכנון לעולים חדשים ותושבים חוזרים',
    'tax.olim.body': 'עולים חדשים ותושבים חוזרים עשויים להיות זכאים להקלות מסוימות, כולל הקלת דיווח ל-10 שנים במקרים מסוימים, בכפוף לכללי זכאות. אנו עוזרים לבנות תזמון ותיעוד לתמיכה במעבר תואם למערכת המס הישראלית.',
    'tax.faq.q1': 'האם אני יכול לשלם מס רכישה ישראלי במטבע חוץ?',
    'tax.faq.a1': 'מיסים משולמים בדרך כלל בשקלים (ש"ח). אנו מנחים לקוחות לגבי תזמון, לוגיסטיקת המרה ושוברי תשלום כדי שהכספים יגיעו בזמן ובצורה הנדרשת.',
    'tax.faq.q2': 'האם הבנק הישראלי יקבל את ההעברה שלי אוטומטית?',
    'tax.faq.a2': 'תאימות לעולם אינה אוטומטית. העברות גדולות מפעילות בדיקות. אנו מכינים את תיק "מקור הכספים" מראש כדי להפחית את הסיכון להקפאה או דחייה של כספים.',
    'tax.faq.q3': 'מתי אני הופך לתושב מס בישראל?',
    'tax.faq.a3': 'תושבות נקבעת על ידי מבחן "מרכז החיים", לא רק אזרחות. אנו מייעצים לגבי הקריטריונים המשפטיים וכיצד הנוכחות שלכם בישראל משפיעה על הסטטוס שלכם.',
    'tax.cta.title': 'תאימות אסטרטגית',
    'tax.cta.body': 'התחילו עם בהירות, תוכנית שהופכת אי ודאות למציאות.',
    'tax.cta.button': 'תיאום שיחת ייעוץ',

    // Olim & Returning Residents Page
    'olim.hero.title': 'ייעוץ משפטי לעולים חדשים ותושבים חוזרים',
    'olim.hero.subtitle': 'מסגרת משפטית מובנית למעבר שלכם לישראל. מיצוב מס, רכישת נכס ושילוב נכסים.',
    'olim.context.title': 'פרק חדש מובנה מהיום הראשון',
    'olim.context.body': 'התחלת פרק חדש בישראל מביאה הזדמנות, מורכבות ובחירות משפטיות חשובות. המשרד מספק הדרכה משפטית סבלנית, אישית ומובנית לעולים חדשים ותושבים חוזרים, מבטיח שכל לקוח מרגיש נתמך, מיודע ובטוח מהצעד הראשון ואילך.',
    'olim.context.body2': '',
    'olim.framework.title': 'ניהול משפטי של תהליך המעבר',
    'olim.framework.planning.title': 'ייעוץ טרום עלייה',
    'olim.framework.planning.desc': 'בחינת סטטוס התושבות והשלכותיו המשפטיות טרם המעבר הפיזי במטרה למקסם את זכויות הלקוח.',
    'olim.framework.property.title': 'מימוש הטבות מס לעולים חדשים',
    'olim.framework.property.desc': 'ניהול הדיווח לרשויות המס בגין רכישת נכס ראשון או העברת הון תוך ניצול מקסימלי של הקלות המס המוקנות בחוק.',
    'olim.framework.banking.title': 'הסדרת נכסים וזכויות',
    'olim.framework.banking.desc': 'בדיקת נאותות משפטית לנכסים הנרכשים בישראל והתאמתם למבנה הפיננסי החדש של הלקוח כתושב ישראל.',
    'olim.framework.peace.title': 'תמיכה דו לשונית חוצת גבולות',
    'olim.framework.peace.desc': 'המשרד מתקשר בעברית ובאנגלית ומתאם עם יועצים זרים של הלקוח לפי הצורך. המטרה היא לתרגם תהליכים משפטיים ישראליים מורכבים לצעדים ברורים ומעשיים.',
    'olim.tax.title': 'מיצוב מס לעולים חדשים ותושבים חוזרים',
    'olim.tax.body': 'עולים (מהגרים חדשים) ותושבים חוזרים (תושב חוזר ותיק) עשויים להיות זכאים להקלות מס ודיווח ספציפיות, בכפוף לכללי זכאות וסיווג. תזמון ותיעוד נכונים קריטיים לאבטחת הטבות אלו.',
    'olim.tax.body2': 'אנו עוזרים ללקוחות למפות את הסטטוס שלהם, לסמן שיקולים רלוונטיים ולתאם עם אנשי מקצוע במס בעת הצורך כדי לתמוך במעבר תואם ולהפחית חשיפה שניתן להימנע ממנה.',
    'olim.clients.title': 'הלקוחות שלנו סומכים עלינו',
    'olim.clients.body': 'עמוד זה מיועד ליחידים ומשפחות העוברים לישראל שמעריכים תהליך מובנה וממוקד תאימות במיוחד כאשר מעורבים נכסים משמעותיים, הכנסה זרה או מוטבים חוצי גבולות.',
    'olim.expect.title': 'מה לצפות',
    'olim.expect.body': 'ההתקשרות מתחילה עם רשימת תיעוד, מיפוי סטטוס (פרופיל תושבות ומס) ומפת דרכים מתואמת עם שלבים מוגדרים.',
    'olim.expect.item1': 'רשימת תיעוד מותאמת למצבכם',
    'olim.expect.item2': 'מיפוי סטטוס תושבות ומס',
    'olim.expect.item3': 'מפת דרכים מתואמת עם שלבים מוגדרים',
    'olim.cta.title': 'התחילו את המעבר על בסיס יציב',
    'olim.cta.body': 'התחילו עם מפת דרכים מובנית ורשימת תיעוד.',
    'olim.cta.button': 'תיאום שיחת ייעוץ',

    // Commercial & Civil Page
    'commercial.hero.title': 'מסחרי ואזרחי',
    'commercial.hero.subtitle': 'הגנה על אינטרסים עסקיים באמצעות חוזים ממושמעים וייצוג בישראל לעניינים חוצי גבולות.',
    'commercial.philosophy.title': 'דיוק לפני סכסוכים',
    'commercial.philosophy.body': 'בהתקשרויות מסחריות, עוצמת העמדה שלכם תלויה בדיוק החוזים שלכם. בין אם מנסחים הסכם שותפות או מנהלים משא ומתן על יציאה, אנו מעריכים כל עניין דרך שלוש עדשות. זכויות חוזיות, חשיפה פיננסית ואכיפה עתידית.',
    'commercial.philosophy.body2': 'המשרד מספק ניתוח משפטי ממושמע בסכסוכים חוזיים ועסקיים. כל עניין נבחן דרך זכויות חוזיות, חשיפה פיננסית וסעדים זמינים. הלקוחות מקבלים הדרכה מובנית שתומכת במשא ומתן, יישוב סכסוכים או הליכים משפטיים רשמיים בעת הצורך.',
    'commercial.services.title': 'ניהול סיכונים וייצוג אינטרסים עסקיים',
    'commercial.services.contracts.title': 'ניסוח וסקירת חוזים מסחריים',
    'commercial.services.contracts.desc': 'בניית תשתית חוזית הכוללת מנגנוני הגנה על השקעות וניטרול חשיפות מבעוד מועד.',
    'commercial.services.negotiation.title': 'ייצוג חברות ומשקיעים זרים',
    'commercial.services.negotiation.desc': 'המשרד משמש נציגות משפטית אופרטיבית בישראל עבור גופים הפועלים מחוץ למדינה הכולל אכיפת פסקי חוץ וניהול זכויות בעלי מניות.',
    'commercial.services.dispute.title': 'אסטרטגיית יישוב סכסוכים',
    'commercial.services.dispute.desc': 'ניהול מחלוקות חוזיים מתוך ראייה עסקית רחבה המעדפת את האינטרס הכלכלי של הלקוח בין אם בליטיגציה נחושה ובין אם בחתירה לפשרה מושכלת.',
    'commercial.services.crossborder.title': 'תיעוד חוצה גבולות',
    'commercial.services.crossborder.desc': 'תיאום עם עורכי דין בחו"ל והתאמת חוזים ופסקי דין זרים לאכיפה או הכרה בישראל.',
    'commercial.crossborder.title': 'אינטרסים עסקיים מעבר לגבולות',
    'commercial.crossborder.body': 'אנו מנהלים עניינים מסחריים עם מרכיבים בינלאומיים, משמשים כזרוע המשפטית המקומית עבור המשקיעים והעסקים של לקוחותינו. גישה מובנית זו תומכת בלקוחות המתגוררים בחו"ל אך שומרים על אינטרסים פעילים בישראל.',
    'commercial.crossborder.body2': 'בין אם אוכפים חוזה זר בישראל או מגנים על אינטרסים של בעל מניות מקומי בזמן שהייה בחו"ל, אנו מספקים ייצוג מעשי על הקרקע לעניינים אזרחיים עם מימדים בינלאומיים. הפרקטיקה מתאמת דרישות משפטיות ישראליות עם עורכי דין זרים ואסטרטגיה חוצית גבולות, תומכת בלקוחות המתגוררים בחו"ל או שומרים על קשרים משפטיים ופיננסיים במספר תחומי שיפוט.',
    'commercial.clients.title': 'עם מי אנחנו בדרך כלל עובדים',
    'commercial.clients.body': 'הפרקטיקה המסחרית שלנו מתמקדת בחוזים, הגנה על נכסים וסכסוכים מורכבים, ומשרתת הן עסקים והן יחידים פרטיים. אנו עובדים עם בעלי עסקים, משקיעים, מנהלים ולקוחות פרטיים הזקוקים לייעוץ משפטי שוטף או פתרון אסטרטגי לעניינים מסחריים ואזרחיים משמעותיים.',
    'commercial.cta.title': 'הגנו על האינטרסים המסחריים שלכם',
    'commercial.cta.body': 'התחילו בסקירת חוזה או הערכת אסטרטגיית סכסוך. חסוי ומתועד.',
    'commercial.cta.button': 'תיאום שיחת ייעוץ',
  },
};

// NOTE: Keep a stable Context instance across hot-reloads to avoid "must be used within a Provider" errors.
// This is especially important in development, since we frequently edit translations.
const _global = globalThis as unknown as {
  __mayaLanguageContext?: React.Context<LanguageContextType | undefined>;
};

const LanguageContext =
  _global.__mayaLanguageContext ?? createContext<LanguageContextType | undefined>(undefined);

_global.__mayaLanguageContext = LanguageContext;

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('maya-ziv-lang');
    return (saved as Language) || 'en';
  });

  const isRTL = language === 'he';

  const setLanguage = useCallback((lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('maya-ziv-lang', lang);
  }, []);

  useEffect(() => {
    document.documentElement.dir = isRTL ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language, isRTL]);

  const t = useCallback((key: string): string => {
    return translations[language][key] || key;
  }, [language]);

  const contextValue = useMemo(() => ({
    language,
    setLanguage,
    t,
    isRTL
  }), [language, t, isRTL]);

  return (
    <LanguageContext.Provider value={contextValue}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};